import type { Metadata } from "next";
import "./globals.css";
import { BrowseNavLink } from "@/components/BrowseNavLink";


export const metadata: Metadata = {
  title: "AI Interview Simulator | Candidate Screening System",
  description:
    "AI-Powered Role-Based Interview Simulator. Upload your resume, pick a role, and get personalized technical questions generated by a RAG pipeline.",
  keywords: ["AI interview", "technical interview", "RAG", "candidate screening"],
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="page-wrapper">
        {/* ── Header ─────────────────────────────────────── */}
        <header
          style={{
            borderBottom: "1px solid rgba(255,255,255,0.06)",
            background: "rgba(13,15,23,0.85)",
            backdropFilter: "blur(12px)",
            position: "sticky",
            top: 0,
            zIndex: 50,
          }}
        >
          <div
            style={{
              maxWidth: 1200,
              margin: "0 auto",
              padding: "0 1.25rem",
              height: 60,
              display: "flex",
              alignItems: "center",
              gap: "0.75rem",
            }}
          >
            {/* Logo mark */}
            <div
              style={{
                width: 32,
                height: 32,
                borderRadius: 8,
                background: "linear-gradient(135deg, #6366f1, #22d3ee)",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                flexShrink: 0,
              }}
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none">
                <path
                  d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"
                  stroke="white"
                  strokeWidth="2"
                  strokeLinecap="round"
                  strokeLinejoin="round"
                />
              </svg>
            </div>

            <div>
              <h1
                style={{
                  fontSize: "0.9375rem",
                  fontWeight: 700,
                  color: "#e2e8f0",
                  lineHeight: 1.2,
                }}
              >
                Candidate Screening
              </h1>
              <p
                style={{
                  fontSize: "0.6875rem",
                  color: "#6366f1",
                  fontWeight: 500,
                  letterSpacing: "0.05em",
                  textTransform: "uppercase",
                }}
              >
                AI-Powered • RAG Pipeline
              </p>
            </div>

            <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: "12px" }}>
              <BrowseNavLink />
              <span className="badge badge-accent" style={{ fontSize: "0.6875rem" }}>
                ⚡ Live
              </span>
            </div>
          </div>
        </header>

        {/* ── Main Content ───────────────────────────────── */}
        <main className="page-container">{children}</main>

        {/* ── Subtle background grid ─────────────────────── */}
        <div
          aria-hidden="true"
          style={{
            position: "fixed",
            inset: 0,
            zIndex: -1,
            backgroundImage:
              "linear-gradient(rgba(99,102,241,0.03) 1px, transparent 1px), linear-gradient(90deg, rgba(99,102,241,0.03) 1px, transparent 1px)",
            backgroundSize: "64px 64px",
            pointerEvents: "none",
          }}
        />
      </body>
    </html>
  );
}
